### ISSUE TITLE
视频还是没办法插入notion呢

### ISSUE THREAD

**Issue by leftchest** [myl7/onedrive-vercel-index#1]
测试了下大大网盘里的视频直链地址依然无法插入notion，恳请指导下如何解决
https://share.myl.moe/api?path=/videos/bilibili/%E3%80%90%E8%99%B9%E8%99%B9%E6%95%99%E8%82%B2%E5%87%BA%E7%89%88%E7%A4%BE%E3%80%91%E4%B8%BE%E4%B8%80%E5%8F%8D%E4%B8%89%20%E8%A7%A6%E7%B1%BB%E6%97%81%E9%80%9A%20%E7%BB%83%E4%B9%A0%E5%85%A8%E9%9B%86%20%E5%90%AB%E4%BE%8B%E9%A2%98%E8%AF%A6%E8%A7%A3/BV1Rq4y1s71o.mp4&raw=true

**Comment by myl7** [comment]
这个链接就可以被 Notion 识别了：

https://share.myl.moe/api/name/a.mp4?path=/videos/bilibili/%E3%80%90%E8%99%B9%E8%99%B9%E6%95%99%E8%82%B2%E5%87%BA%E7%89%88%E7%A4%BE%E3%80%91%E4%B8%BE%E4%B8%80%E5%8F%8D%E4%B8%89%20%E8%A7%A6%E7%B1%BB%E6%97%81%E9%80%9A%20%E7%BB%83%E4%B9%A0%E5%85%A8%E9%9B%86%20%E5%90%AB%E4%BE%8B%E9%A2%98%E8%AF%A6%E8%A7%A3/BV1Rq4y1s71o.mp4&raw=true

你可以对比一下看看需要自己改的部分。
你如果急需这个功能的话，可以先从我这个 repo fork 先用着。
不过我这个 fork 暂只做开发用，不能提供完善的后续维护，之后如果上游添加了这功能的话，你还需要再去上游重新 fork 一趟。
如果能等几天的话（这个项目还是很活跃的，不会等十天半个月的），等上游加了再说也行。

**Comment by leftchest** [comment]
感谢指导

**Comment by myl7** [comment]
目前上游 https://github.com/spencerwooo/onedrive-vercel-index 已经添加了此功能了
